micronaut:
  application:
    name: delay_api
  executors:
    io:
      type: fixed
      nThreads: 75
  server:
    port: 8000
    maxRequestSize: 1MB
    host: localhost
    netty:
      worker:
        threads: 1
      childOptions:
        autoRead: true

